"""empty message

Revision ID: 5d8ad67cd122
Revises: 
Create Date: 2019-07-18 14:20:20.132138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8ad67cd122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('vrn', sa.String(length=9), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('vrn')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.create_table('vat_returns',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('period_key', sa.String(length=4), nullable=True),
    sa.Column('vat_due_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_due_acquisitions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_vat_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_reclaimed_curr_period', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_vat_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value_sales_ex_vat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value_purchases_ex_vat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value_goods_supplied_ex_vat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value_acquisitions_ex_vat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('finalised', sa.Boolean(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('vat_returns')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('organisations')
    # ### end Alembic commands ###
