"""empty message

Revision ID: 8ccfb761b3c0
Revises: 33ec398793a7
Create Date: 2019-07-19 08:16:24.004000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ccfb761b3c0'
down_revision = '33ec398793a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vat_returns', sa.Column('submitted_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vat_returns', 'submitted_on')
    # ### end Alembic commands ###
